name: Cypress Regression Suite Parallel Execution
on:
  workflow_dispatch:
    inputs:
      containers:
        description: "Containers"
        required: true
      run_title:
        description: Cypress run title
        required: true
        default: Manually triggered run
# on:
#   schedule:
#     - cron: '*/60 * * * *'
# on:
#   push: 
#     branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.value }}
    steps:
      - name: Generate unique ID
        id: uuid
        # take the current commit + timestamp together
        # the typical value would be something like "sha-5d3fe...35d3-time-1620841214"
        run: echo "::set-output name=value::sha-$GITHUB_SHA-time-$(date +"%s")"

      - name: Print unique ID
        run: echo "generated id ${{ steps.uuid.outputs.value }}"
  get-containers:
    name: get-containers
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.set-containers.outputs.containers }}
    steps:
      - uses: actions/checkout@v2
      - name: set container
        id: set-containers
        run: |
          for (( i=1; i <= ${{ github.event.inputs.containers }}; i++ ))
          do
            arr+="$i,"
          done
          echo "::set-output name=containers::["${arr[@]::-1}"]"

  cypress-run:
    runs-on: self-hosted
    needs: ["get-containers", "prepare"]
    timeout-minutes: 1000
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: ${{fromJson(needs.get-containers.outputs.containers)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y wget xvfb libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2
    - name: Download Chrome
      run: sudo wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Install Chrome
      run: sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
    - name: Chrome Browser run
      uses: cypress-io/github-action@v4
      with:
        start: npm run
        browser: chrome
        wait-on-timeout: 300
        record: true
        parallel: true
        ci-build-id: ${{ needs.prepare.outputs.uuid }}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    - name: Upload screenshot for failed Test Scripts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots

    - name: Upload video artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos